export enum RepetierServerEvents {
	OPEN = "open",
	MESSAGE = "message",
	DISCONNECTED = "disconnected",
	ERROR = "error",
}

export enum Actions {
	EXTEND_PING = "extendPing",
	PING = "ping",
	LIST_PRINTER = "listPrinter",
	SEND = "send",
	STATE_LIST = "stateList",
	RESPONSE = "response",
	MOVE = "move",
	MESSAGES = "messages",
	REMOVE_MESSAGE = "removeMessage",
	REMOVE_MODEL = "removeModel",
	LIST_MODELS = "listModels",
	COPY_MODEL = "copyModel",
	LIST_JOBS = "listJobs",
	MODEL_INFO = "modelInfo",
	JOB_INFO = "jobInfo",
	START_JOB = "startJob",
	STOP_JOB = "stopJob",
	CONTINUE_JOB = "continueJob",
	REMOVE_JOB = "removeJob",
	GET_PRINTER_CONFIG = "getPrinterConfig",
	SET_PRINTER_CONFIG = "setPrinterConfig",
	GET_SCRIPT = "getScript",
	SET_SCRIPT = "setScript",
	ACTIVATE = "activate",
	DEACTIVATE = "deactivate",
	COMMUNICATION_DATA = "communicationData",
	GET_EEPROM = "getEeprom",
	SET_EEPROM = "setEeprom",
	LIST_EXTERNAL_COMMANDS = "listExternalCommands",
	RUN_EXTERNAL_COMMAND = "runExternalCommand",
	CREATE_CONFIGURATION = "createConfiguration",
	REMOVE_CONFIGURATION = "removeConfiguration",
}
